### PR TITLE
Removing unused code and files

### LINKED ISSUE #97: Remove unused code
docs/dev/* etc. seems unused or?

### PR DESCRIPTION
**Pull request by jahzielv**
**What this PR does / why we need it**:
Getting rid of unused files/code.

**Which issue this PR fixes**
fixes #97

### CODE REVIEW

**Comment by jahzielv** [comment]
I've deleted the docs/dev directory - anything else we wanna clean up with this PR?

**Comment by stp-ip** [comment]
I'm currently traveling, so maybe @ArmanMazdaee can already help out.

**Comment by ArmanMazdaee** [comment]
Thanks for removing the codes. I think we could remove the whole docs/ folder.
Thanks for the PR.

**Comment by jahzielv** [comment]
The docs/ folder has been removed - anything else to clean out?

**Comment by ArmanMazdaee** [comment]
LGTM :+1: :

**Pull request merged**
