### PR TITLE
Use array for positions

### LINKED ISSUE #86: Use array for positions?
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature

Should we switch from a single position to an array of positions instead, where the default usage would be a single string within the array?
LinkedIn and Angellist both use multiple positions. Example: "Founder, CTO".

### PR DESCRIPTION
**Pull request by jahzielv**
**What this PR does / why we need it**:
Changes `position` to be an array of strings representing different job positions.

fixes #86

### CODE REVIEW

**Comment by jahzielv** [comment]
This PR currently only changes `work.position` from a string to an array. `position` is a member of several other sections (`references`, `volunteer`); do we want to change all of those as well?

**Comment by jahzielv** [comment]
Any ideas as to why this build is failing? According to Travis:
```
--- FAIL: TestRenderRun (0.21s)
    render_test.go:23: Could not render the resume html: remote repository is empty
```
Why would the render command create this error? I've been tracing through calls but haven't found anything that sticks out.

**Comment by stp-ip** [comment]
Did you look into: https://github.com/resumic/schema/blob/a810c874c164e3439e47211f925e4e47141cf1eb/cmd/render_test.go?

**Comment by stp-ip** [comment]
Happy to take a deeper dive in the coming days, if necessary. Also looping in @ArmanMazdaee and @erbesharat for additional help, if needed.

**Comment by stp-ip** [comment]
Just checking in. Did the render_test.go file help in figuring out the failing tests?

@ArmanMazdaee Care to take a look?

**Pull request closed without merging**
