### PR TITLE
Add ui.json

### PR DESCRIPTION
**Pull request by ArmanMazdaee**
**What this PR does / why we need it**:
Add a basic hardcoded version of ui.json file

### CODE REVIEW

**Comment by stp-ip** [comment]
Will check it out with Syna later. Looking forward to testing Resumic. I can finally create my own resume :D

**Comment by stp-ip** [comment]
This is a start, but I assume you haven't tested this with the Syna editor.
Also didn't see any discussions with Mahdi on this. 

Happy to merge this to get the order added, but this needs a lot more thought and work.
Not user friendly, breaks in Syna and hard to navigate.

**Comment by stp-ip** [comment]
Deployed Syna example: https://confident-varahamihira-2d1026.netlify.com/

**Comment by stp-ip** [comment]
We might be able to derive some of the UI stuff from our struct. What do you think? Or we can also keep it hard coded for now.

This is also using an outdated schema.json file.

A few things that I think should be improved as a first step:
* Placeholders
* Descriptions
* Field/section names need to be more descriptive as "volunteer" is not that meaningful -> could be "Volunteer activities" etc.
* Meta data doesn't need to be shown as this is entered by software
* Dates should be using ISO 8601 standard aka YYYY-MM-DD (date picker has the wrong format)

The first 2 things come back to us not having fixed the consistency. Example data, which could be used as placeholders, and descriptions. These are still conflated and need to be cleaned up in our code.

Later we should add a custom component for location, which can translate a street address or such into lat/long. This should only be used on the backend and not shown to the user.

**Comment by stp-ip** [comment]
Sidenote: UI fails for volunteer and skills sections.

How did you test this change? Maybe the test setup is different.

**Comment by stp-ip** [comment]
As mentioned the editor from http://registry.jsonresume.org/ might be a good start.

**Comment by ArmanMazdaee** [comment]
The hardcoded `ui.json` now contains the ordering and placeholders. I have tested it against [react-jsonschema-form](https://mozilla-services.github.io/react-jsonschema-form/) and it seems it has some problem with `uri-reference`. Everything else seems fine.

**Pull request merged**
