### PR TITLE
[WIP] Adding verbose output for validate command

### LINKED ISSUE #91: Add verbose output for validate
**Is this a BUG REPORT or FEATURE REQUEST?**:
feature
              
**What happened**:
Currently validate only checks if the resume is valid from a schema perspective.
This has a few downsides. First we allow quite a bit of optional additions so a typo in a key field usually won't be caught.

**What you expected to happen**:
Add additional verbose outputs. 
1. What sections and their subsections/items are missing?
  Reason: What might be missing could be later used for themes to show what data might be filled out.
2. What additional data is in the resume file, but not in the default schema?
  Reason: We are not perfectly strict on the schema and therefore having the ability to see how a data file differs from the actual schema might be helpful for the user and later for us. When someone creates a patch and want to upstream, they can easily showcase the use case by sending us the diff)

**Anything else we need to know?**:
Not sure if these should just be shown be default or be separate commands.

### PR DESCRIPTION
**Pull request by jahzielv**
**What this PR does / why we need it**:
Adds functionality for getting more verbose output from the `validate` command. Specifically, output will include output regarding:

1. **What sections and their subsections/items are missing?**
Reason: What might be missing could be later used for themes to show what data might be filled out.

2. **What additional data is in the resume file, but not in the default schema?**
Reason: We are not perfectly strict on the schema and therefore having the ability to see how a data file differs from the actual schema might be helpful for the user and later for us. When someone creates a patch and want to upstream, they can easily showcase the use case by sending us the diff)

fixes #91

### CODE REVIEW

**Comment by jahzielv** [comment]
@stp-ip, what do you envision exactly for the verbose output on `validate`? I'm tinkering around with the error details, and there's a lot of stuff that could be displayed, but I'm not sure what your vision is for it. Right now, the error messages when you have non-specified fields are pretty explicit, telling you where the error is and what type it is. Would we want something more than that?

**Comment by stp-ip** [comment]
Generally I had a diff like output in mind, but not sure, if that works perfectly.
Basically it would show your resume data with green text for correct and red for error and orange for recommended.

If anything is recommended, but not currently set within the specific resume it could add the structure within this diff and display it as orange saying recommended, but not set/filled or so.

But that was a really really broad idea. So happy to go a first step with error based output and then maybe render that error based output into a visual representation later on. Both are valid representations and good to keep for accessibility reasons.

Hope that helps :)

**Comment by jahzielv** [comment]
Oh ok gotcha! The errors currently are pretty verbose about telling you exactly where at what the problems are (ie you're missing a required field or you have an additional field that isn't allowed), so I'll go ahead and start working on the diff view!

**Comment by stp-ip** [comment]
Happy to split the PR. One for the verbose error reporting and one adding a visual representation. Don't want to hold up code, that is already available.

**Comment by jahzielv** [comment]
That might be a better strategy. As far as verbose output (not visual diff) goes, did you want anything more than what the errors give now? They currently give a pretty detailed description, telling you what parts of the schema you either forgot to include or where you've added in extra stuff that doesn't belong.

**Comment by stp-ip** [comment]
I only see you adding the verbose flag, but not any code to make it verbose or am I missing something?

**Comment by jahzielv** [comment]
Haha, that was my bad for not explaining. The code in this branch right now is just me experimenting with adding flags, not actually adding any additional verbosity to the error messages.
When I referred to


> That might be a better strategy. As far as verbose output (not visual diff) goes, did you want anything more than what the errors give now? They currently give a pretty detailed description, telling you what parts of the schema you either forgot to include or where you've added in extra stuff that doesn't belong.

I meant what the errors given by the code without any change to them.

**Comment by stp-ip** [comment]
Thanks for clarifying. So I would consider this branch as still WIP.
Happy to close this, if you feel the current verbosity is enough and we can open a visual one separately.

**Comment by jahzielv** [comment]
I think the current verbosity is pretty good; @ArmanMazdaee what's your opinion?

If we all agree, I'm down to close and open up a new issue targeting a visual diff.

**Comment by stp-ip** [comment]
Closing for now and we can always reiterate, if @ArmanMazdaee or someone else feels differently.

**Pull request closed without merging**
